# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa98f9dbb3fd2e31de487bcaec4d710fa8a8f9681d9da6487a3f04e91168c692f749f5255b68e9baa0dd2a9daf53ef509fbe1c42bed1be1a98c368191a1ca2b5

test:
  secret_key_base: 9f7e02289d3d5aa0090abc7e063d2bd6ba3f1f098391702d94d25c6cf60b978451ef09689b7462328b421f1a75cff9cb25f6e6ebf5a4f681800d5816497964ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
